package schema

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"testing"
)

var update = flag.Bool("update", false, "regenerate testdata/golden.json from the fixtures")

const goldenPath = "testdata/golden.json"

type goldenBlob struct {
	Pattern string `json:"pattern"`
	CID     string `json:"cid"`
}

type goldenVector struct {
	Name string `json:"name"`
	Type string `json:"type"`
	CBOR string `json:"cbor_hex"`
	CID  string `json:"cid"`
}

type goldenFile struct {
	Comment string         `json:"_comment"`
	Blobs   []goldenBlob   `json:"blobs"`
	Vectors []goldenVector `json:"vectors"`
}

const goldenComment = "CID stability golden vectors (spec 13.2). Generated by " +
	"`go test ./schema -update`; these CIDs are frozen forever -- a diff here means the " +
	"wire format changed and every published root would move. blobs[] pins BlobCID over a " +
	"BlobSize buffer of the repeated pattern byte; the blobs themselves are not stored."

// TestGoldenVectors anchors the wire format. It asserts three things per
// vector: the fixture encodes to the recorded bytes, those bytes hash to the
// recorded CID, and decoding them re-encodes to exactly the same bytes.
func TestGoldenVectors(t *testing.T) {
	fs := fixtures(t)
	if *update {
		writeGolden(t, fs)
	}

	data, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("reading %s (regenerate with `go test ./schema -update`): %v", goldenPath, err)
	}
	var golden goldenFile
	if err := json.Unmarshal(data, &golden); err != nil {
		t.Fatalf("parsing %s: %v", goldenPath, err)
	}

	byName := make(map[string]goldenVector, len(golden.Vectors))
	for _, v := range golden.Vectors {
		byName[v.Name] = v
	}

	t.Run("blobs", func(t *testing.T) {
		if len(golden.Blobs) != len(blobPatterns) {
			t.Fatalf("golden has %d blob entries, fixtures use %d", len(golden.Blobs), len(blobPatterns))
		}
		for i, pattern := range blobPatterns {
			want := golden.Blobs[i]
			if got := blobPatternName(pattern); got != want.Pattern {
				t.Errorf("blobs[%d] pattern = %s, want %s", i, got, want.Pattern)
			}
			if got := blobCIDFor(t, pattern).String(); got != want.CID {
				t.Errorf("BLOB CID CHANGED for pattern %s:\n got %s\nwant %s", want.Pattern, got, want.CID)
			}
		}
	})

	seen := make(map[string]bool, len(fs))
	for _, f := range fs {
		seen[f.name] = true
		t.Run(f.name, func(t *testing.T) {
			want, ok := byName[f.name]
			if !ok {
				t.Fatalf("no golden vector named %q; regenerate with `go test ./schema -update`", f.name)
			}
			if got := fixtureKind(f.obj); got != want.Type {
				t.Fatalf("fixture kind = %q, golden says %q", got, want.Type)
			}

			block, c, err := encodeFixture(f.obj)
			if err != nil {
				t.Fatalf("encode: %v", err)
			}
			if got := hex.EncodeToString(block); got != want.CBOR {
				t.Errorf("ENCODING CHANGED:\n got %s\nwant %s", got, want.CBOR)
			}
			if got := c.String(); got != want.CID {
				t.Errorf("CID CHANGED:\n got %s\nwant %s", got, want.CID)
			}

			raw, err := hex.DecodeString(want.CBOR)
			if err != nil {
				t.Fatalf("golden cbor_hex is not hex: %v", err)
			}
			// The recorded CID must be the hash of the recorded bytes, or the
			// vector is internally inconsistent and proves nothing.
			hashed, err := NodeCID(raw)
			if err != nil {
				t.Fatalf("NodeCID: %v", err)
			}
			if hashed.String() != want.CID {
				t.Errorf("golden vector is inconsistent: bytes hash to %s but cid says %s", hashed, want.CID)
			}

			decoded, err := decodeFixture(want.Type, raw)
			if err != nil {
				t.Fatalf("decoding golden bytes: %v", err)
			}
			reblock, rec, err := encodeFixture(decoded)
			if err != nil {
				t.Fatalf("re-encoding golden bytes: %v", err)
			}
			if !bytes.Equal(raw, reblock) {
				t.Errorf("golden bytes did not survive decode/re-encode:\n got %x\nwant %x", reblock, raw)
			}
			if rec.String() != want.CID {
				t.Errorf("CID after decode/re-encode = %s, want %s", rec, want.CID)
			}
		})
	}

	for _, v := range golden.Vectors {
		if !seen[v.Name] {
			t.Errorf("golden vector %q has no fixture; it can never fail. Remove it or restore the fixture", v.Name)
		}
	}
}

func writeGolden(t *testing.T, fs []fixture) {
	t.Helper()
	out := goldenFile{Comment: goldenComment}
	for _, pattern := range blobPatterns {
		out.Blobs = append(out.Blobs, goldenBlob{
			Pattern: blobPatternName(pattern),
			CID:     blobCIDFor(t, pattern).String(),
		})
	}
	for _, f := range fs {
		block, c, err := encodeFixture(f.obj)
		if err != nil {
			t.Fatalf("encoding fixture %q: %v", f.name, err)
		}
		out.Vectors = append(out.Vectors, goldenVector{
			Name: f.name,
			Type: fixtureKind(f.obj),
			CBOR: hex.EncodeToString(block),
			CID:  c.String(),
		})
	}

	data, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		t.Fatalf("marshalling golden: %v", err)
	}
	data = append(data, '\n')
	if err := os.MkdirAll("testdata", 0o755); err != nil {
		t.Fatalf("creating testdata: %v", err)
	}
	if err := os.WriteFile(goldenPath, data, 0o644); err != nil {
		t.Fatalf("writing %s: %v", goldenPath, err)
	}
	t.Logf("wrote %s (%d vectors)", goldenPath, len(out.Vectors))
}

func blobPatternName(pattern byte) string { return fmt.Sprintf("0x%02x", pattern) }
